### ISSUE TITLE
Issue building on Windows

### ISSUE THREAD

**Issue by reut2** [DX-MON/crunch#7]
This is the output of the 'ninja -C build' command: 

ninja: Entering directory `build'
[2/42] Compiling C object crunch/libcrunch-1.dll.p/StringFuncs.c.obj
In file included from ../crunch/StringFuncs.c:2:
../crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
[3/42] Compiling C object crunch/libcrunch-1.dll.p/ArgsParser.c.obj
In file included from ../crunch/ArgsParser.c:7:
../crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
../crunch/ArgsParser.c: In function 'parseArguments':
../crunch/ArgsParser.c:104:21: warning: implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Wimplicit-function-declaration]
  104 |     argRet->value = strdup(argv[i]);
      |                     ^~~~~~
      |                     strcmp
../crunch/ArgsParser.c:104:19: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  104 |     argRet->value = strdup(argv[i]);
      |                   ^
../crunch/ArgsParser.c:131:25: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  131 |       argRet->params[j] = strdup(argv[i + j + 1]);
      |                         ^
../crunch/ArgsParser.c:156:18: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  156 |    argRet->value = strdup(argv[i]);
      |                  ^
[5/42] Compiling C object crunch/crunch.exe.p/crunch.c.obj
FAILED: crunch/crunch.exe.p/crunch.c.obj
"gcc" "-Icrunch\crunch.exe.p" "-Icrunch" "-I..\crunch" "-fdiagnostics-color=always" "-DNDEBUG" "-pipe" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-Wextra" "-Wpedantic" "-std=c11" "-O3" "-DWIN32" "-D_WINDOWS" "-pthread" -MD -MQ crunch/crunch.exe.p/crunch.c.obj -MF "crunch\crunch.exe.p\crunch.c.obj.d" -o crunch/crunch.exe.p/crunch.c.obj "-c" ../crunch/crunch.c
In file included from ../crunch/threading/threadShim.h:19,
                 from ../crunch/crunch.c:2:
..\crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
../crunch/crunch.c: In function 'tryRegistration':
../crunch/crunch.c:168:35: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
  168 |  const registerFn registerTests = (registerFn)dlsym(testSuite, "registerTests");
      |                                   ^
../crunch/crunch.c: In function 'main':
../crunch/crunch.c:284:2: warning: implicit declaration of function '_set_invalid_parameter_handler' [-Wimplicit-function-declaration]
  284 |  _set_invalid_parameter_handler(invalidHandler);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../crunch/crunch.c:285:2: warning: implicit declaration of function '_CrtSetReportMode' [-Wimplicit-function-declaration]
  285 |  _CrtSetReportMode(_CRT_ASSERT, 0);
      |  ^~~~~~~~~~~~~~~~~
../crunch/crunch.c:285:20: error: '_CRT_ASSERT' undeclared (first use in this function); did you mean 'C_ASSERT'?
  285 |  _CrtSetReportMode(_CRT_ASSERT, 0);
      |                    ^~~~~~~~~~~
      |                    C_ASSERT
../crunch/crunch.c:285:20: note: each undeclared identifier is reported only once for each function it appears in
../crunch/crunch.c:286:20: error: '_CRT_ERROR' undeclared (first use in this function); did you mean 'GCP_ERROR'?
  286 |  _CrtSetReportMode(_CRT_ERROR, 0);
      |                    ^~~~~~~~~~
      |                    GCP_ERROR
[6/42] Compiling C object crunch/libcrunch-1.dll.p/Core.c.obj
In file included from ../crunch/Core.c:7:
../crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
[7/42] Compiling C object crunch/libcrunch-1.dll.p/threading_threadShim.c.obj
In file included from ../crunch/threading/threadShim.h:19,
                 from ../crunch/threading/threadShim.c:1:
..\crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
[8/42] Compiling C object crunch/libcrunch-1.dll.p/Logger.c.obj
In file included from ../crunch/threading/threadShim.h:19,
                 from ../crunch/Core.h:5,
                 from ../crunch/Logger.c:6:
..\crunch/crunch.h:44: warning: "__cdecl" redefined
   44 | #define __cdecl __attribute__((cdecl))
      |
<built-in>: note: this is the location of the previous definition
[10/42] Compiling C++ object crunch++/libcrunch++-1.dll.p/argsParser.cxx.obj
ninja: build stopped: subcommand failed.

**Comment by DX-MON** [comment]
Thank you - could I also get the output of `meson build` as this tells me how the build was set up

**Comment by DX-MON** [comment]
I've given this a decently long time for you to answer, and without reproduction steps (`meson configure` output or the `meson build` configuration used) I can't work on fixing this so I'm going to have to close the issue.

Please open a new one with this output attached so I can work on the issue.
